-- =====================================================================================
-- DevStrider — shared peer database (PostgreSQL)
--
-- Run this by hand against the shared database. The desktop app issues NO DDL: it will
-- not create, alter, or drop anything. If a table is missing, Settings → Peer database →
-- Test connection says so by name.
--
-- Safe to re-run: every statement is guarded.
--
-- This database may be shared with other applications. Nothing below touches any table
-- outside the three DevStrider owns.
-- =====================================================================================


-- =====================================================================================
-- SECTION 1 — clean up an earlier DevStrider schema  (SKIP THIS IF UNSURE)
--
-- Only needed if peer_users / peer_bids / peer_interviews already exist in the older
-- shape (peer_users keyed by username, rows carrying owner_username). It DESTROYS the
-- peer data in those three tables.
--
-- Nothing else is affected — but check first:
--     SELECT count(*) FROM peer_bids;
-- If that returns 0, there is nothing to lose. If it errors, the tables don't exist yet
-- and you can skip straight to Section 2.
--
-- Uncomment the three lines to use them.
-- =====================================================================================

-- DROP TABLE IF EXISTS peer_bids;
-- DROP TABLE IF EXISTS peer_interviews;
-- DROP TABLE IF EXISTS peer_users;      -- last: the other two reference it


-- =====================================================================================
-- SECTION 2 — the schema
-- =====================================================================================

-- One row per DevStrider install. This is what makes a teammate discoverable before
-- they've pushed a single bid.
CREATE TABLE IF NOT EXISTS peer_users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     TEXT        NOT NULL UNIQUE,   -- the upsert matches on this
    email        TEXT        NOT NULL DEFAULT '',
    -- [{"Slug":"fernando-garcia","Name":"Fernando Garcia"}, ...] — the bidding identities
    -- this user owns. Slug joins to owner_profile_slug below.
    profiles     JSONB       NOT NULL DEFAULT '[]'::jsonb,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL
);


-- Bid summaries. `id` is the MongoDB ObjectId hex from the author's local database, so
-- row identity is stable on both sides and every write can be an idempotent upsert.
CREATE TABLE IF NOT EXISTS peer_bids (
    id                 TEXT PRIMARY KEY,
    owner_user_id      BIGINT      NOT NULL REFERENCES peer_users(id) ON DELETE CASCADE,
    owner_profile_slug TEXT        NOT NULL DEFAULT '',
    owner_profile_name TEXT        NOT NULL DEFAULT '',
    company            TEXT        NOT NULL DEFAULT '',
    role               TEXT        NOT NULL DEFAULT '',
    status             TEXT        NOT NULL DEFAULT '',
    origin             TEXT        NOT NULL DEFAULT '',
    resume_id          TEXT        NOT NULL DEFAULT '',   -- the UID from the fast-feed line
    primary_stacks     TEXT[]      NOT NULL DEFAULT '{}',
    job_description    TEXT        NOT NULL DEFAULT '',
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL,              -- drives the delta pull
    first_created_at   TIMESTAMPTZ NOT NULL,
    applied_at         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_peer_bids_updated ON peer_bids (updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_peer_bids_owner   ON peer_bids (owner_user_id, updated_at DESC);


-- Interview rounds. Every round of one hiring process shares a process_id, so a pipeline
-- reads as one thing rather than as loose rounds.
CREATE TABLE IF NOT EXISTS peer_interviews (
    id                 TEXT PRIMARY KEY,
    owner_user_id      BIGINT      NOT NULL REFERENCES peer_users(id) ON DELETE CASCADE,
    owner_profile_slug TEXT        NOT NULL DEFAULT '',
    owner_profile_name TEXT        NOT NULL DEFAULT '',
    process_id         TEXT        NOT NULL DEFAULT '',
    company            TEXT        NOT NULL DEFAULT '',
    role               TEXT        NOT NULL DEFAULT '',
    interview_type     TEXT        NOT NULL DEFAULT '',
    status             TEXT        NOT NULL DEFAULT '',
    recruiter          TEXT        NOT NULL DEFAULT '',
    resume_id          TEXT        NOT NULL DEFAULT '',
    job_description    TEXT        NOT NULL DEFAULT '',
    scheduled_date     TIMESTAMPTZ,                        -- null until a date is set
    scheduled_time     TEXT        NOT NULL DEFAULT '',
    duration_minutes   INTEGER,
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_peer_ivs_updated ON peer_interviews (updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_peer_ivs_owner   ON peer_interviews (owner_user_id, scheduled_date);
CREATE INDEX IF NOT EXISTS ix_peer_ivs_process ON peer_interviews (process_id);


-- =====================================================================================
-- SECTION 3 — verify
-- =====================================================================================

-- Expect exactly three rows.
SELECT tablename
  FROM pg_tables
 WHERE schemaname = 'public'
   AND tablename IN ('peer_users', 'peer_bids', 'peer_interviews')
 ORDER BY tablename;


-- =====================================================================================
-- Notes
--
-- • All timestamps are TIMESTAMPTZ and always written as UTC. Npgsql rejects a DateTime
--   whose Kind isn't UTC for these columns, so the app stamps every value before sending.
--
-- • No foreign key from peer_bids to a profile: profile slug and name are denormalised
--   onto each row so the Peers grid renders without a join, and so a renamed profile
--   doesn't orphan history.
--
-- • What is NOT here, by design: job URLs, generated resume text, resume files, meeting
--   links, comments, and local profile config (Word template path, macro name, prompt).
--   Those never leave the author's machine.
--
-- • Renaming a username creates a NEW peer_users row, because username is the upsert's
--   conflict target. Old rows keep pointing at the old id.
-- =====================================================================================
