-- =====================================================================================
--  DevStrider — shared PostgreSQL schema
--
--  Complete, current, and self-contained: drop the three tables and recreate them.
--  Run this whole file in your SQL editor. DevStrider itself issues NO DDL, so this file
--  is the only thing that defines the shared database.
--
--  Requires DevStrider 7.3.0 or later (peer_interviews carries the R2 resume pointers).
-- =====================================================================================
--
--  ⚠ THIS DATABASE IS SHARED WITH ANOTHER APPLICATION.
--
--  The DROP statements below name DevStrider's three tables explicitly and nothing else.
--  Never replace them with anything that enumerates tables — a wildcard drop here would
--  take out roughly fifty tables belonging to someone else's project.
--
--  ⚠ DROPPING DELETES EVERY PEER'S DATA, NOT JUST YOURS.
--
--  The shared tables are the only copy of other people's bids and interviews on this
--  server. Your own rows survive — they live in your local MongoDB and re-upload on the
--  next sync — but a teammate's do not come back unless they sync again.
--
--  AFTERWARDS, ON EVERY MACHINE: Sharing tab → "Re-send everything".
--  Sync progress is one timestamp per machine, not a flag per row, so an install that
--  already pushed will believe its data is here and push nothing. That button clears the
--  marker. Skipping it is why the tables looked permanently empty last time.
--
--  Resume FILES are unaffected: they live in Cloudflare R2, and these tables only hold
--  the object keys pointing at them.
-- =====================================================================================


-- ── 0. Drop ─────────────────────────────────────────────────────────────────────────
-- Reverse dependency order. CASCADE also removes the foreign keys pointing in.
DROP TABLE IF EXISTS peer_interviews CASCADE;
DROP TABLE IF EXISTS peer_bids       CASCADE;
DROP TABLE IF EXISTS peer_users      CASCADE;


-- ── 1. Identities ───────────────────────────────────────────────────────────────────
-- One row per (person, profile) — NOT per person.
--
-- A bid has to name the profile it was sent under, and profile names change. Storing the
-- name as text on every bid means a rename silently splits one identity's history in two.
-- Giving each (person, profile) pair its own row lets bids reference it by id: the name
-- lives in exactly one place, and renaming it carries every historical bid along.
CREATE TABLE peer_users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     TEXT        NOT NULL,
    profile_slug TEXT        NOT NULL,          -- stable key; survives a display-name change
    profile_name TEXT        NOT NULL DEFAULT '',
    email        TEXT        NOT NULL DEFAULT '',
    -- DevStrider writes this explicitly; the default is for anything else touching the table.
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL,
    -- What the upsert matches on. profile_slug alone can't be unique — two people can both
    -- have a profile slugged "default" — which is also why bids can't reference it directly.
    CONSTRAINT peer_users_identity_key UNIQUE (username, profile_slug)
);

-- "All profiles belonging to this person" — the Peers tab's user → profile picker.
CREATE INDEX ix_peer_users_username ON peer_users (username);


-- ── 2. Bids ─────────────────────────────────────────────────────────────────────────
-- `id` is the MongoDB ObjectId hex from the author's local database, so row identity is
-- stable on both sides and every write can be an idempotent upsert.
CREATE TABLE peer_bids (
    id                 TEXT PRIMARY KEY,
    -- Points at one peer_users row, which IS a (person, profile) pair — so this single
    -- column gives you both. The profile name is deliberately NOT copied here.
    owner_user_id      BIGINT      NOT NULL REFERENCES peer_users(id) ON DELETE CASCADE,
    company            TEXT        NOT NULL DEFAULT '',
    role               TEXT        NOT NULL DEFAULT '',
    status             TEXT        NOT NULL DEFAULT '',
    origin             TEXT        NOT NULL DEFAULT '',
    resume_id          TEXT        NOT NULL DEFAULT '',   -- the UID from the fast-feed line
    primary_stacks     TEXT[]      NOT NULL DEFAULT '{}',
    job_description    TEXT        NOT NULL DEFAULT '',
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL,              -- drives the delta pull
    first_created_at   TIMESTAMPTZ NOT NULL,
    applied_at         TIMESTAMPTZ                        -- NULL while still a draft
);

CREATE INDEX ix_peer_bids_updated ON peer_bids (updated_at DESC);
CREATE INDEX ix_peer_bids_owner   ON peer_bids (owner_user_id, updated_at DESC);


-- ── 3. Interviews ───────────────────────────────────────────────────────────────────
-- Every round of one hiring process shares a process_id, so a pipeline reads as one thing
-- rather than as loose rounds.
CREATE TABLE peer_interviews (
    id                 TEXT PRIMARY KEY,
    owner_user_id      BIGINT      NOT NULL REFERENCES peer_users(id) ON DELETE CASCADE,
    -- The bid this interview came from, when there was one. NULL is meaningful: a
    -- linkedin_chat-origin interview genuinely has no bid behind it, which '' could not say.
    -- ON DELETE SET NULL rather than CASCADE — losing the bid must not erase the interview.
    bid_id             TEXT        REFERENCES peer_bids(id) ON DELETE SET NULL,
    process_id         TEXT        NOT NULL DEFAULT '',
    company            TEXT        NOT NULL DEFAULT '',
    role               TEXT        NOT NULL DEFAULT '',
    interview_type     TEXT        NOT NULL DEFAULT '',
    status             TEXT        NOT NULL DEFAULT '',
    recruiter          TEXT        NOT NULL DEFAULT '',
    resume_id          TEXT        NOT NULL DEFAULT '',
    job_description    TEXT        NOT NULL DEFAULT '',
    scheduled_date     TIMESTAMPTZ,                        -- NULL until a date is set
    scheduled_time     TEXT        NOT NULL DEFAULT '',
    duration_minutes   INTEGER,                            -- NULL when unknown
    -- Pointer to the resume file in Cloudflare R2, not the file itself. The bytes stay in
    -- object storage and every DevStrider user downloads them with their own credentials,
    -- which is what keeps this database small. Empty means nothing was attached.
    resume_object_key  TEXT        NOT NULL DEFAULT '',
    resume_file_name   TEXT        NOT NULL DEFAULT '',
    created_at         TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL
);

CREATE INDEX ix_peer_ivs_updated ON peer_interviews (updated_at DESC);
CREATE INDEX ix_peer_ivs_owner   ON peer_interviews (owner_user_id, scheduled_date);
CREATE INDEX ix_peer_ivs_process ON peer_interviews (process_id);
CREATE INDEX ix_peer_ivs_bid     ON peer_interviews (bid_id);


-- ── 4. Verify ───────────────────────────────────────────────────────────────────────
-- Expect 7, 13 and 18 columns. Anything else means part of this file didn't run.
SELECT table_name, count(*) AS columns
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN ('peer_users', 'peer_bids', 'peer_interviews')
GROUP BY table_name
ORDER BY table_name;

-- For a column-by-column check against what the app writes, run shared-db-verify.sql.
